shell = "zsh"

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"

[plugins.git-alias]
github = "chivalryq/git-alias"

[plugins.alias-tips]
github= "djui/alias-tips"

[plugins.completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.sanekeybinds]
github = "embeddedpenguin/sanekeybinds"

[plugins.zsh-mise]
github = "wintermi/zsh-mise"
